version: "3"
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: EventTransitUI
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - mongo
    environment: 
      - ASPNETCORE_ENVIRONMENT=production
      - MongoDb__Host=mongo
      - RabbitMq__Endpoint=amqp://guest:guest@rabbitmq:5672/
    restart: always

  rabbitmq:
    container_name: eventransit_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  mongo:
    container_name: eventransit_mongo
    image: mongo
    ports:
      - "27017:27017"
      
