FROM mcr.microsoft.com/dotnet/sdk:5.0 AS builder
WORKDIR /source

COPY . .

# Change the Directory
WORKDIR /source/

# aspnet-core
RUN dotnet restore src/EvenTransit.Api/EvenTransit.Api.csproj
RUN dotnet publish src/EvenTransit.Api/EvenTransit.Api.csproj --output /eventransitapi/ --configuration Release

## Runtime
FROM mcr.microsoft.com/dotnet/aspnet:5.0

# Change the Directory
WORKDIR /eventransitapi

COPY --from=builder /eventransitapi .
ENTRYPOINT ["dotnet", "EvenTransit.Api.dll"]