version: "3"
services:
  ui:
    image: ciceksepeti/eventransit
    container_name: EventTransitUI
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - MongoDb__Host=mongo
      - RabbitMq__Endpoint=amqp://guest:guest@rabbitmq:5672/
    restart: always

  rabbitmq:
    container_name: eventransit_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"  

  mongo:
    build: ./ci-test/mongodb
    container_name: mongo
    ports:
      - "27017:27017"
