name: CI

on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: techciceksepeti/onbuild:latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: sh ./scripts/ci-build.sh

      - name: Compose up
        run: |
          docker build -t mountebank -f ./ci-test/imposters/Dockerfile.mountebank .
          docker-compose up -d rabbitmq
          docker-compose up -d ui
          docker-compose up wait-for-it

      - name: Integration tests
        run: |
          docker run --network container:EventTransitUI \
              postman/newman_ubuntu1404 run https://api.postman.com/collections/18070358-d9c53e91-a367-469a-8ce3-c4c40498fd3c?access_key=PMAT-01HQJ5Y0PG7HR9R108Q66WJWCV

      - name: Push image
        env:
          GCR_REGISTRY_ID: ${{ secrets.GCR_REGISTRY_ID }}
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
          DOCKER_LOGIN_USER: ${{ secrets.DOCKER_LOGIN_USER }}
          DOCKER_LOGIN_PASS: ${{ secrets.DOCKER_LOGIN_PASS }}
          TRIGGER_FUNCTION: ${{ secrets.TRIGGER_FUNCTION }}
          TRIGGER_REGION: ${{ secrets.TRIGGER_REGION }}
          GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
        run: sh ./scripts/ci-push.sh
