name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    container:
      image: techciceksepeti/onbuild:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build image
        run: sh ./cicd/ci-build.sh


      # Runs a set of commands using the runners shell
      - name: Push image
        env:
          AWS_REGISTRY_ID: ${{ secrets.AWS_REGISTRY_ID }}
          GCR_REGISTRY_ID: ${{ secrets.GCR_REGISTRY_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: sh ./cicd/ci-push.sh
