name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: techciceksepeti/onbuild:latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'keyfile.json'
          fileDir: '/tmp/'
          encodedString: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Push image
        env:
          GCR_REGISTRY_ID: ${{ secrets.GCR_REGISTRY_ID }}
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: sh ./scripts/ci-push.sh

      # - name: Build image
      #   run: sh ./scripts/ci-build.sh

      # - name: Compose up
      #   run: docker-compose up -d ui

      # - name: Push image
      #   env:
      #     GCR_REGISTRY_ID: ${{ secrets.GCR_REGISTRY_ID }}
      #     GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #   run: sh ./scripts/ci-push.sh
