name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: techciceksepeti/onbuild:latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: sh ./cicd/ci-build.sh


      - name: Push image
        env:
          AWS_REGISTRY_ID: ${{ secrets.AWS_REGISTRY_ID }}
          GCR_REGISTRY_ID: ${{ secrets.GCR_REGISTRY_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: sh ./cicd/ci-push.sh
